//semrush error codes  
const semRushErrorCodeDesc = 
{
9: 'Pages not crawled', 
10: 'DNS resolution issue', 
11: 'We couldn\'t open the page?s URL', 
12: 'Broken external links', 
13: 'Broken internal images', 
14: 'Broken external images', 
15: 'Duplicate meta descriptions', 
16: 'Invalid robots.txt format', 
17: 'Invalid sitemap.xml format', 
18: 'Incorrect pages found in sitemap.xml', 
19: 'www resolve issues', 
20: 'Viewport not configured', 
21: 'Large HTML page size', 
22: 'Missing canonical tags in AMP pages', 
23: 'Issues with hreflang values', 
24: 'Hreflang conflicts within page source code', 
25: 'Issues with incorrect hreflang links', 
26: 'Non-secure pages', 
27: 'Certificate Expiration', 
28: 'Old security protocol version', 
29: 'Certificate registered to incorrect name', 
30: 'Issues with mixed content', 
31: 'Links lead to HTTP pages for HTTPS site', 
32: 'Neither canonical URL nor 301 redirect from HTTP h...', 
33: 'Redirect chains and loops', 
34: 'AMP Pages with HTML Issues', 
35: 'AMP Pages with Style and Layout Issues', 
36: 'AMP Pages with Templating Issues', 
38: 'Broken canonical URLs', 
39: 'Multiple canonical URLs', 
40: 'Meta refresh redirects', 
41: 'Broken internal JavaScript and CSS files', 
42: 'Insecure encryption algorithms', 
43: 'Sitemap file too large', 
101: 'Title element is too short', 
102: 'Title element is too long', 
103: 'Missing h1', 
104: 'Multiple h1 tags', 
105: 'Duplicate content in h1 and title', 
106: 'Missing meta description', 
108: 'Too many on-page links', 
109: 'Temporary redirects', 
110: 'Missing ALT attributes', 
111: 'Slow page load speed', 
112: 'Low text to HTML ratio', 
113: 'Too many URL parameters', 
114: 'Missing hreflang and lang attributes', 
115: 'Encoding not declared', 
116: 'Doctype not declared', 
117: 'Low word count', 
120: 'Flash content used', 
121: 'Frames used', 
122: 'Underscores in URL', 
123: 'Nofollow attributes in internal links', 
124: 'Sitemap.xml not specified in robots.txt', 
125: 'Sitemap.xml not found', 
126: 'HTTP encryption not used', 
127: 'No SNI support', 
128: 'HTTP URLs in sitemap.xml for HTTPS site', 
129: 'Uncompressed pages', 
130: 'Disallowed internal resources', 
131: 'Uncompressed JavaScript and CSS files', 
132: 'Uncached JavaScript and CSS files', 
133: 'Too large JavaScript and CSS total size', 
134: 'Too many JavaScript and CSS files', 
135: 'Unminified JavaScript and CSS files', 
201: 'Too long URLs', 
202: 'Nofollow attributes in external links', 
203: 'Robots.txt not found', 
204: 'Hreflang language mismatch issues', 
205: 'No HSTS support', 
206: 'Orphaned pages (Google Analytics)', 
207: 'Orphaned sitemap pages', 
208: 'Pages have high Document Interactive Time', 
209: 'Blocked by X-Robots-Tag: noindex HTTP header', 
210: 'Disallowed external resources', 
211: 'Broken external JavaScript and CSS files', 
212: 'Page crawl depth', 
213: 'Pages with only one internal link', 
214: 'Permanent redirects', 
215: 'Resources formatted as page links'
}